### ISSUE TITLE
内容は commentというより content の方が良いかもしれません。

### ISSUE THREAD

**Issue by norotime** [niceblow/PhotoAlbum#11]
https://github.com/niceblow/PhotoAlbum/blob/d45216c20778edfccb69b28b03809352fe3a3e7f/db/schema.rb#L24

**Comment by niceblow** [comment]
commentは、写真に対する撮影者のコメントを格納するカラムに位置付けています。
トップページ検索フォームのラベルもコメントとしておりますが、
それでもカラム名はcontentが良いですか？
