### ISSUE TITLE
メソッドチェインできないか検討する

### ISSUE THREAD

**Issue by norotime** [niceblow/PhotoAlbum#2]
https://github.com/niceblow/PhotoAlbum/blob/d45216c20778edfccb69b28b03809352fe3a3e7f/app/controllers/albums_controller.rb#L7

```
.result.order('id DESC')
```
こちらチェインできませんでしたか？

**Comment by niceblow** [comment]
@searchは検索フォーム出力時に使用されている為、
検索結果を返すメソッド「.result.order('id DESC')」をチェインしてしまうと
フォーム表示エラーになってしまうようです。
もし認識違いがありましたらご指摘願います。
